### ISSUE TITLE
[Feature Request]x- series extensions support

### ISSUE THREAD

**Issue by ipfans** [swaggest/openapi-go#23]
E.g. [`x-codeSamples`](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-codesamples) is a extension for OpenAPI, it is not standard. 

There are some extension tags that very useful for generate docs from code. So it should be a new feature or just I missed something that can do this?

**Comment by vearutop** [comment]
Hi @ipfans, sorry for late reply. 

Extensions can be added with [`Operation.WithMapOfAnything`](https://pkg.go.dev/github.com/swaggest/openapi-go@v0.2.10/openapi3#Operation.WithMapOfAnything) for a full map of extensions, or [`Operation.WithMapOfAnythingItem`](https://pkg.go.dev/github.com/swaggest/openapi-go@v0.2.10/openapi3#Operation.WithMapOfAnythingItem) for a single item, or assigning directly to `MapOfAnything` property.

Please note that functions `With*` are mutating original receiver.

```go
op.WithMapOfAnythingItem("x-codeSamples", CodeSample{Lang:"Go", Source:"a:=1"})
```

All the types that support `x-` extensions have these symbols available.

**Comment by ipfans** [comment]
@vearutop Thanks, I got it.
