### ISSUE TITLE
Support OAS3.1 ?

### ISSUE THREAD

**Issue by deBarrosS** [swaggest/openapi-go#37]
As described in [this article ](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) by the OpenAPI Initiative , there are a few changes from OAS3.0 to OAS3.1. 
I might be wrong but it seems that the majority of them should not be that hard to implement.

- Example -> Examples
- Nullable -> type list containing null as element
- [GET and HEAD requests payloads allowed](https://github.com/swagger-api/swagger-ui/issues/2136). (Still need to implement the ForceRequestBody() function)
- File Upload Payload descriptions

Is there any intention of handling these changes soon (or at all)?

**Comment by vearutop** [comment]
Main challenge of 3.1 upgrade is to support latest JSON schema as definition language. OpenAPI entities in this library are automatically [generated](https://github.com/swaggest/openapi-go/blob/v0.2.18/Makefile#L45) and generator tool also needs an upgrade to latest JSON schema.

This whole epic is definitely on my list, but I'm not sure when I will have capacity to work through it.

**Comment by deBarrosS** [comment]
I'm not 100% sure whether I'll be able to work through it now either, but would any contribution be appreciated?

**Comment by vearutop** [comment]
Contributions are welcome of course, but I think on-boarding might be quite complicated (due to dependency on code generation from original schema).

**Comment by daveshanley** [comment]
If anyone is interested, https://github.com/pb33f/libopenapi has support for OAS3.1

**Comment by vearutop** [comment]
> If anyone is interested, https://github.com/pb33f/libopenapi has support for OAS3.1

Cool project, the support here is also on the way: https://github.com/swaggest/openapi-go/tree/openapi31.

Just one thing to note is that using OpenAPI 3.1 now might be a little inconvenient due to lack of support even in "standard" tooling (to my knowledge, Swagger UI does not support OpenAPI 3.1 yet), not to mention 3rd party tools.

But we need to get there anyways.
