### ISSUE TITLE
Is there any support for oneOf, anyOf etc... If so how would we do it

### ISSUE THREAD

**Issue by AdamJSoftware** [swaggest/openapi-go#39]
Is there any support for oneOf, anyOf etc... If so how would we do it. I feel like one or two examples would help clarify this.

Overall, great project!

**Comment by vearutop** [comment]
Thank you for nice feedback!

You can define `*Of` constraints by either implementing an [`*Exposer`](https://pkg.go.dev/github.com/swaggest/jsonschema-go#AnyOfExposer) interface of using [helper function](https://pkg.go.dev/github.com/swaggest/jsonschema-go#AnyOf) with value samples. See more details at https://github.com/swaggest/jsonschema-go#implementing-interfaces-on-a-type.
