### ISSUE TITLE
Improving the regular expression used to remove gorilla.mux-style regexp in paths

### ISSUE THREAD

**Issue by Fifi31** [swaggest/openapi-go#45]
Hello,
Imagine I have the 2 routes in my API : `/users/{userID:[^/]+}` and `/users/{userID:[^/]+}/books/{bookID:.+}`.
The regexp are `[^/]+` because without it, calling `users/toto/books/openapi`, matches with `/users/{userID:[^/]+}` with userID being `toto/books/openapi`.

The problem is that during `Spec.SetupOperation()`, `{userID:[^/]+}` is not matched by `regexFindPathParameter` (`{([^}:]+)(:[^/]+)?(?:})`).

I think changing the regex to `{([^}:]+)(:[^}]+)?(?:})` would solve the problem.

**Comment by vearutop** [comment]
Thank you, please try `v0.2.22`.

**Comment by Fifi31** [comment]
Thanks, I briefly tested it but it is still not working. I will dig deeper in it when I have time.

**Comment by Fifi31** [comment]
Hey @vearutop I had the chance to look at it, and it works well. Thanks for everything !
