### ISSUE TITLE
[Question] Is there a way to select if a struct schema is a ref or not ?

### ISSUE THREAD

**Issue by Fifi31** [swaggest/openapi-go#54]
Hello,

I noticed that every schema is put in `reflector.Spec.Components.Schemas.MapOfSchemaOrRefValues`, even structs that are fields of other structs, which are referenced in `reflector.Spec.Components.Schemas.MapOfSchemaOrRefValues["Struct"].Schema.Properties["Field"].Schema.Items.SchemaReference`.

Is there some options that can be used so schemas of fields of structs are set in `reflector.Spec.Components.Schemas.MapOfSchemaOrRefValues["Struct"].Schema.Properties["Field"].Schema.Items.Schema` directly ?

It is just a question, no problem if it is not possible.

**Comment by vearutop** [comment]
I'm sorry, I don't understand. 😅 

Could you make a small example to clarify expectations?

**Comment by vearutop** [comment]
And btw, since this is a question it is better to move to discussions so that the topic is more visible to other people that may have same question.

**Comment by Fifi31** [comment]
I didn't know the discussions feature on github, I will switch to it and provide an example !
