### ISSUE TITLE
Doc page gets 404 when getting swagger-ui assets 

### ISSUE THREAD

**Issue by paul-england** [swaggest/openapi-go#81]
In the console of the docs page, it attempts to GET a few js/css files (from Cloudflare) and fails (404). The result is the page renders white.  Is there a way to to use an alternative?

Here is the output from my console.
```
GET https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.19.1/swagger-ui.css net::ERR_ABORTED 404
docs:34     GET https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.19.1/swagger-ui-standalone-preset.js net::ERR_ABORTED 404
docs:33     GET https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.19.1/swagger-ui-bundle.js net::ERR_ABORTED 404
docs:63 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (docs:63:5)
```

**Comment by paul-england** [comment]
Worth noting, the above is for an in-progress project that has some features I'll obviously need to look at.  Copy / pasting the example from `README.md`, I get the following in the console, but the page renders, so obviously better.

```
DevTools failed to load source map: Could not load content for http://localhost:8011/docs/swagger-ui-bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8011/docs/swagger-ui-standalone-preset.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8011/docs/swagger-ui.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by paul-england** [comment]
Using `v3cdn` fixes this issue. Sorry to spam the board.

**Comment by vearutop** [comment]
Missing source maps are expected, as they are optional for the web app to function and only needed to debug frontend code.

However, both cdn and non-cdn packages from render Swagger UI properly.

**Comment by paul-england** [comment]
For the record, using `v3cdn` or `v5cdn` both render the page just fine. `v4cdn`, for my project, does not.  I'm fine w/ ticking up to `v5`.

**Comment by vearutop** [comment]
Could you share some details to reproduce the issue?

**Comment by vearutop** [comment]
Oh, very interesting.

https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.19.1/swagger-ui-bundle.js is indeed 404, apparently it was removed from CDN for some reason. Thank you for the report, I'll downgrade `v4cdn` to [`4.18.3`](https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.3/swagger-ui-bundle.js) that still exists.

**Comment by vearutop** [comment]
Fixed in https://github.com/swaggest/swgui/releases/tag/v1.7.3.

**Comment by paul-england** [comment]
Excellent! Thanks for the help.  Great project, btw.
